### ISSUE TITLE
Unpin  wasmtime requirement?

### ISSUE THREAD

**Issue by ecederstrand** [Kanaries/gw-dsl-parser-py#15]
Is there any reason that  wasmtime is pinned to 12.0.0 in the requirements? I have a different package that requires  wasmtime>=13.0.0 so I cannot install the two packages at the same time.

**Comment by longxiaofei** [comment]
I will update requirements for wasmtime version.

**Comment by ecederstrand** [comment]
Thanks! I see the requirement was updated and the change released in https://pypi.org/project/gw-dsl-parser/0.1.49/. Closing.
